name: test

on:
  pull_request:
  workflow_run:
    workflows:
      - update-snapshot
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Restore node_modules
        uses: actions/cache@v4
        id: node-cache-restore
        with:
          path: node_modules
          key: dependencies-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        if: steps.node-cache-restore.outputs.cache-hit != 'true'
      - name: Lint code
        run: npm run lint
      - name: Build code
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Upload screenshots of tests
        uses: actions/upload-artifact@v4
        # テスト結果に関わらずスクリーンショットをアップロードする
        if: ${{ failure() || !failure() }}
        with:
          name: test-screenshots
          path: tmp/screenshot
