name: update snapshot test of jest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Restore node_modules
        uses: actions/cache@v4
        id: node-cache-restore
        with:
          path: node_modules
          key: dependencies-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        if: steps.node-cache-restore.outputs.cache-hit != 'true'
      - name: Build code
        run: npm run build
      - name: Run tests
        run: npm run test:update
      - name: Commit updated snapshots
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f spec/__snapshots__
          git commit -m "Update snapshots by GitHub Action"
          git push
